export const startingPages: Record<string, string> = {
  'Default': '',
  'Home': 'FEmusic_home',
  'Explore': 'FEmusic_explore',
  'New Releases': 'FEmusic_new_releases',
  'Charts': 'FEmusic_charts',
  'Moods & Genres': 'FEmusic_moods_and_genres',
  'Library': 'FEmusic_library_landing',
  'Playlists': 'FEmusic_liked_playlists',
  'Songs': 'FEmusic_liked_videos',
  'Albums': 'FEmusic_liked_albums',
  'Artists': 'FEmusic_library_corpus_track_artists',
  'Subscribed Artists': 'FEmusic_library_corpus_artists',
  'Uploads': 'FEmusic_library_privately_owned_landing',
  'Uploaded Playlists': 'FEmusic_liked_playlists',
  'Uploaded Songs': 'FEmusic_library_privately_owned_tracks',
  'Uploaded Albums': 'FEmusic_library_privately_owned_releases',
  'Uploaded Artists': 'FEmusic_library_privately_owned_artists',
};
